### ISSUE TITLE
adapting dnds-clonesize for other datasets

### ISSUE THREAD

**Issue by faizjab** [marcjwilliams1/dnds-clonesize#11]
Hi, 

I hope you are well. I am looking to apply dnds-clonesize to other datasets. I have managed to get good model fits for the sample dataset (oesophagus and skin) however I am trying to apply this to other datasets and getting very poor model fits. 

I am wondering if I need to change the values of the variables in the model, to get a good fit? 

e.g. these variables:
lambda - rate of cell division per unit time
r - probability of symmetric divisions
r*lambda
A - area
p - density of the stem cells per mm2
t - time
u - mutation rate 

Would they require altering to get a good fit?

As far as I can tell this information was not available in the Oesophagus paper from Martincorena (https://www.science.org/doi/10.1126/science.aau3879) and am wondering how you modelled this?

Any help would be greatly appreciated 

Kind regards, 
Faiz

**Comment by marcjwilliams1** [comment]
Hi, here's a bit more information on these parameters:

r*lambda - this is the loss/replacement rate of stem cells and one of the inferred parameters in the model
A - area - The martincorena data had areas of the sequenced biopsies somewhere in the supplementary tables
p - density of the stem cells per mm2 set to 5,000/mm2
t - time - age of the patients (given in martincorena datasets)
u - mutation rate not relevant

Relevant sections in the paper you might want to take a look at
- Page 4 & 6
- Page 11 & 12 of methods

If this is not data from the oesophagus or skin then some things that come to mind:
- p might be different
- The stem cell model might not be appropriate. The model defined in the section `Frequency-dependent dN/dS values in stem cell populations` was well supported by some prior studies, but in tissue that have more defined anotomical structures it might not be appropriate. Stem cells in the colon for [example](https://www.cell.com/cell-reports/fulltext/S2211-1247(14)00588-9?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2211124714005889%3Fshowall%3Dtrue) fit a different model due to the crypts that make up the epithelia

Feel free to email me if you want any more advice.
